version: '3.6'  # technically 3.7, but it's not supported everywhere

# --update structure to newer suggestions:
# restart-policy



services:
  # ...

  mqtt_switcher:
    # build is tagged with image automatically
    build: .
    image: modischfabrications/mqtt_switcher:latest
    restart: unless-stopped
    # no external ports needed
    devices:
      # GPIO access
      - /dev/mem/:/dev/mem/
    #      - /dev/gpiomem/:/dev/gpiomem/
    volumes:
      # resolved to absolute path, relative paths will convert to directory
      # TODO: try https://docs.docker.com/compose/compose-file/#configs
      - $(pwd)/config.yml:/config.yml

  # ...

