version: '3'

# --update structure to newer suggestions:
# restart-policy



services:

  mqtt_switcher:
    # build is tagged with image automatically
    build: .
    image: modischfabrications/mqtt_switcher:latest
    restart: unless-stopped
    # no external ports needed
    volumes:
      # GPIO access
      - /dev/mem/:/dev/mem/
      # config
      - # TODO: try https://docs.docker.com/compose/compose-file/#configs
      - $(pwd)/config.yml:/config.yml


