version: '3'

# --update structure to newer suggestions:
# restart-policy



services:

  mqtt_switcher:
    image: modischfabrications/mqtt_switcher:latest
    restart: unless-stopped
    # no external ports needed
    volumes:
      # GPIO access
      - /dev/mem/:/dev/mem/
      # config
      - ./config.yml:/config.yml


